**NumPy Arrays** - An array is a data structure that **stores values of same data type.**

In [ ]:
import numpy as np

**NumPy Array**

In [ ]:
# defining a list of different car companies or string elements
arr_str = ['Mercedes', 'BMW', 'Audi', 'Ferrari', 'Tesla']

# defining a list of number of cylinders in car or numerical elements
arr_num = [5, 4, 6, 7, 3]

In [ ]:
# connverting the list arr_str to a NumPy array
np_arr_str = np.array(arr_str)

# connverting the list arr_num to a NumPy array
np_arr_num = np.array(arr_num)

# checking the output
print('list (arr_str): ',type(arr_str),arr_str)
print('Numpy Array (arr_str): ',type(np_arr_str),np_arr_str)
print('list (arr_num): ',type(arr_num),arr_num)
print('Numpy Array (arr_num): ',type(np_arr_num),np_arr_num)

list (arr_str):  <class 'list'> ['Mercedes', 'BMW', 'Audi', 'Ferrari', 'Tesla']
Numpy Array (arr_str):  <class 'numpy.ndarray'> ['Mercedes' 'BMW' 'Audi' 'Ferrari' 'Tesla']
list (arr_num):  <class 'list'> [5, 4, 6, 7, 3]
Numpy Array (arr_num):  <class 'numpy.ndarray'> [5 4 6 7 3]


**NumPy Matrix**

* A matrix is a two-dimensional data structure where elements are arranged into rows and columns.
* A matrix can be created by using **list of lists**

In [ ]:
# numpy matrix
matrix = np.array([[1,2,1],[4,5,9],[1,8,9]])
print(matrix)
print('Data type of matrix: ',type(matrix))

[[1 2 1]
 [4 5 9]
 [1 8 9]]
Data type of matrix:  <class 'numpy.ndarray'>


In [ ]:
# 2d array using list of list
d2_lst = [[1,2,8],[4,5,8],[1,8,8]]
print(type(d2_lst))
print(d2_lst)

np_d2_lst = np.array(d2_lst)
print(type(np_d2_lst))
print(np_d2_lst)

<class 'list'>
[[1, 2, 8], [4, 5, 8], [1, 8, 8]]
<class 'numpy.ndarray'>
[[1 2 8]
 [4 5 8]
 [1 8 8]]


In [ ]:
# ndim method tells dimension of the numpy array
matrix.ndim

2

In [ ]:
# shape method tells explicitly tells # or rows and # of columns
matrix.shape

(3, 3)

**Accessing elements of nympy array/matrix**

In [ ]:
matrix[1,0:] # format [row,columns] OR [row range separated by :,column range as :]

array([4, 5, 9])

In [ ]:
matrix[:,1]

array([2, 5, 8])

In [ ]:
type(matrix[:,1])

numpy.ndarray

In [ ]:
matrix[:,1].ndim

1

In [ ]:
matrix.ndim

2

**<code>np.arange()</code>**
* <code>np.arange(start (def 0),stop,step (def 1)</code>

In [ ]:
arr2  = np.arange(start = 0, stop = 10) # 10 will be excluded from the output
print(arr2)

# or

arr2  = np.arange(10,20)
print(arr2)

[0 1 2 3 4 5 6 7 8 9]
[10 11 12 13 14 15 16 17 18 19]


In [ ]:
arr3 = np.arange(10,20).reshape(5,2) # changes the shape after creating an array of 1d
arr3

array([[10, 11],
       [12, 13],
       [14, 15],
       [16, 17],
       [18, 19]])

In [ ]:
arr4 = np.arange(10,20)
print(arr4)

[10 11 12 13 14 15 16 17 18 19]


In [ ]:
print(np.resize(arr4,15)) # see that the array is repeated

[10 11 12 13 14 15 16 17 18 19 10 11 12 13 14]


In [ ]:
print(np.resize(arr4,25)) # see that the array is repeated

[10 11 12 13 14 15 16 17 18 19 10 11 12 13 14 15 16 17 18 19 10 11 12 13
 14]


In [ ]:
# adding a step size of 5 to create an array
arr3  = np.arange(start = 0, stop = 20, step = 5)
arr3

array([ 0,  5, 10, 15])

**<code>np.linspace()</code>**
* The <code>np.linspace()</code> function returns numpy array which are evenly distributed with respect to interval.
* <code>np.linspace(start - included,stop - included,elements)</code>


In [ ]:
matrix2 = np.linspace(0,5) # by default 50 evenly spaced values will be generated between 0 and 5
matrix2

array([0.        , 0.10204082, 0.20408163, 0.30612245, 0.40816327,
       0.51020408, 0.6122449 , 0.71428571, 0.81632653, 0.91836735,
       1.02040816, 1.12244898, 1.2244898 , 1.32653061, 1.42857143,
       1.53061224, 1.63265306, 1.73469388, 1.83673469, 1.93877551,
       2.04081633, 2.14285714, 2.24489796, 2.34693878, 2.44897959,
       2.55102041, 2.65306122, 2.75510204, 2.85714286, 2.95918367,
       3.06122449, 3.16326531, 3.26530612, 3.36734694, 3.46938776,
       3.57142857, 3.67346939, 3.7755102 , 3.87755102, 3.97959184,
       4.08163265, 4.18367347, 4.28571429, 4.3877551 , 4.48979592,
       4.59183673, 4.69387755, 4.79591837, 4.89795918, 5.        ])

In [ ]:
# generating 10 evenly spaced values between 10 and 20
matrix3 = np.linspace(10,20,10)
matrix3

array([10.        , 11.11111111, 12.22222222, 13.33333333, 14.44444444,
       15.55555556, 16.66666667, 17.77777778, 18.88888889, 20.        ])

In [ ]:
np.linspace(10,20,11)

array([10., 11., 12., 13., 14., 15., 16., 17., 18., 19., 20.])

**<code>np.zeros()</code>**

* Returns a matrix filled with zeros of the given shape.
* <code>np.zeros([shape - rows,columns],dtype - def float)</code>

In [ ]:
matrix4 = np.zeros([3,5])
matrix4

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [ ]:
np.zeros([10])

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [ ]:
np.zeros([5],int)

array([0, 0, 0, 0, 0])

**<code>np.ones()</code>**

* Returns a matrix of given shape and type, filled with ones.
* <code>np.ones([shape - rows,columns],dtype - def float)</code>

In [ ]:
matrix5 = np.ones([3,5])
matrix5

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [ ]:
np.ones([2,3],int)

array([[1, 1, 1],
       [1, 1, 1]])

**<code>np.eye()</code>**
* Returns a matrix with ones on the diagonal and zeros elsewhere - identity
* <code>np.eye(n - num of rows and cols,dtype=int)</code>

In [ ]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [ ]:
np.eye(3,dtype=int)

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

**<Code>np.reshape()</code>**

* The shape of an array basically tells the number of elements and dimensions of the array. Reshaping a Numpy array simply means changing the shape of the given array.
* By reshaping an array we can add or remove dimensions or change number of elements in each dimension.
* **Syntax:** <code>array.reshape(shape=tuple) </code>

In [ ]:
# defining an array with values 0 to 9
arr4 = np.arange(0,10)
arr4

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
# reshaping the array arr4 to a 2 x 5 matrix
arr4_reshaped = arr4.reshape((2,5))
arr4_reshaped

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

**Trigonometric functions**

In [ ]:
print('Sine Function:',np.sin(4))
print('Cosine Function:',np.cos(4))
print('Tan Function',np.tan(4))

Sine Function: -0.7568024953079282
Cosine Function: -0.6536436208636119
Tan Function 1.1578212823495775


In [ ]:
arr1 = np.arange(1,5)
arr1

array([1, 2, 3, 4])

In [ ]:
print('Sine Function:',np.sin(arr1))
print('Cosine Function:',np.cos(arr1))
print('Tan Function',np.tan(arr1))

Sine Function: [ 0.84147098  0.90929743  0.14112001 -0.7568025 ]
Cosine Function: [ 0.54030231 -0.41614684 -0.9899925  -0.65364362]
Tan Function [ 1.55740772 -2.18503986 -0.14254654  1.15782128]


**Exponents**

In [ ]:
np.exp(2)

7.38905609893065

In [ ]:
arr5 = np.array([2,4,6])
np.exp(arr5)

array([  7.3890561 ,  54.59815003, 403.42879349])

**Logarithms**

In [ ]:
# by default NumPy takes the base of log as e
np.log(2)

0.6931471805599453

In [ ]:
np.log(arr5)

array([0.69314718, 1.38629436, 1.79175947])

In [ ]:
## log with base 10
np.log10(8)

0.9030899869919435

In [ ]:
np.log10(100)

2.0

**Arithmetic Operations on arrays**

In [ ]:
# arithmetic on lists
lst1 = [1,2,3]
lst2 = [4,5,6]
print(lst1+lst2)

[1, 2, 3, 4, 5, 6]


In [ ]:
# we can +-*/ arrays together

# defining two arrays
arr7 = np.arange(1,6)
print('arr7:', arr7)

arr8 = np.arange(2,7)
print('arr8:', arr8)

arr7: [1 2 3 4 5]
arr8: [2 3 4 5 6]


In [ ]:
print('Addition: ',arr7+arr8)
print('Subtraction: ',arr8-arr7)
print('Multiplication:' , arr7*arr8)
print('Division:', arr7/arr8)
print('Inverse:', 1/arr7)
print('Powers:', arr7**arr8)

Addition:  [ 3  5  7  9 11]
Subtraction:  [1 1 1 1 1]
Multiplication: [ 2  6 12 20 30]
Division: [0.5        0.66666667 0.75       0.8        0.83333333]
Inverse: [1.         0.5        0.33333333 0.25       0.2       ]
Powers: [    1     8    81  1024 15625]


**Operations on Matrices**

In [ ]:
matrix7 = np.arange(1,10).reshape(3,3)
print("matrix7\n",matrix7)

matrix8 = np.eye(3,dtype=int)
print("matrix8\n",matrix8)

matrix7
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
matrix8
 [[1 0 0]
 [0 1 0]
 [0 0 1]]


In [ ]:
print('Addition: \n', matrix7+matrix8)
print('Subtraction: \n ', matrix7-matrix8)
print('Multiplication: \n', matrix7*matrix8) # element by element
print('Division: \n', matrix7/matrix8) # element by element

Addition: 
 [[ 2  2  3]
 [ 4  6  6]
 [ 7  8 10]]
Subtraction: 
  [[0 2 3]
 [4 4 6]
 [7 8 8]]
Multiplication: 
 [[1 0 0]
 [0 5 0]
 [0 0 9]]
Division: 
 [[ 1. inf inf]
 [inf  5. inf]
 [inf inf  9.]]


/var/folders/vq/s1j96hqn2_99q30y1hw_1dgw0000gn/T/ipykernel_62581/949677980.py:4: RuntimeWarning: divide by zero encountered in divide
  print('Division: \n', matrix7/matrix8) # element by element


**Linear algebra matrix multiplication**

In [ ]:
matrix9 = np.arange(1,10).reshape(3,3)
print('First Matrix: \n',matrix9)

matrix10 = np.arange(11,20).reshape(3,3)
print('Second Matrix: \n',matrix10)
print('')
# taking linear algebra matrix multiplication (some may have heard this called the dot product)
print('Multiplication: \n', matrix9 @ matrix10)

First Matrix: 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Second Matrix: 
 [[11 12 13]
 [14 15 16]
 [17 18 19]]

Multiplication: 
 [[ 90  96 102]
 [216 231 246]
 [342 366 390]]


**Transpose of a matrix**

In [ ]:
print(matrix9)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
# taking transpose of matrix
np.transpose(matrix9)

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [ ]:
matrix9.transpose()

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [ ]:
# another way of taking a transpose
matrix9.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

**Function to find minimum and maximum values**

In [ ]:
print(matrix9)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
print('Minimum value: ',np.min(matrix9))

Minimum value:  1


In [ ]:
print('Maximum value: ',np.max(matrix9))

Maximum value:  9


**<code>np.random.rand</code>**

* Returns a random NumPy array whose element(s) are drawn randomly from the uniform distribution over [0,1] (including 0 but excluding 1)
* <code>np.random.rand(d0,d1-optional)</code>

In [ ]:
# Generating random values in an array
rand_mat = np.random.rand(5)
print(rand_mat)

[0.09485046 0.72395824 0.24462762 0.68240458 0.78491053]


In [ ]:
# * Generating random values in a matrix
rand_mat2 = np.random.rand(5,5) # uniform random variable
print(rand_mat2)

[[0.25388354 0.74261542 0.54988808 0.38767047 0.25666907]
 [0.1913051  0.17862634 0.76273523 0.88919834 0.54256921]
 [0.23124714 0.76348726 0.19070014 0.79161209 0.12979254]
 [0.86451207 0.25734958 0.5453685  0.88543698 0.91492479]
 [0.01911895 0.63726686 0.06856147 0.48851749 0.06354001]]


**<code>np.random.randn</code>**

* Returns a random numpy array whose sample(s) are drawn randomly from the standard normal distribution (Mean as 0 and standard deviation as 1)
* <code>np.random.randn(d0,d1)</code>

In [ ]:
# Generating random values in an array
rand_mat2 = np.random.randn(5)
print(rand_mat2)

[ 0.19394891  0.56481224  0.43910636 -0.29390375  0.37924077]


In [ ]:
# Generating random values in a matrix
rand_mat2 = np.random.randn(5,5)
print(rand_mat2)

[[ 1.01021114  0.96939984  1.32493767  0.83436327  0.93864898]
 [ 0.28628207 -0.48864085 -0.4960663   0.53306789  0.09890002]
 [ 0.59028941 -2.18239803 -0.05994845 -0.09240483  1.60972993]
 [-0.74548128  0.65489538 -0.27656782  0.33080471  0.30294921]
 [ 0.66413883  1.69385633 -0.81432345  1.35937701  1.69744873]]


In [ ]:
# Let's check the mean and standard deviation of rand_mat2
print('Mean:',np.mean(rand_mat2))
print('Standard Deviation:',np.std(rand_mat2))

Mean: 0.38973877672033813
Standard Deviation: 0.8952290502494088


*  we can see that the mean is very close to 0 and standard deviation is very close to 1

**<code>np.random.randint</code>**

* Returns a random numpy array whose element(s) are drawn randomly from low (inclusive) to the high (exclusive) range.

* <code>np.random.randint(low-inclusive, high-exclusive, size)</code>

In [ ]:
# Generating random values in an array
rand_mat3 = np.random.randint(1,5,10)
print(rand_mat3)

[1 3 2 1 3 4 4 2 1 4]


In [ ]:
# Generating random values in a matrix
rand_mat3 = np.random.randint(1,10,[5,5])
print(rand_mat3)

[[5 2 4 2 5]
 [6 3 5 8 7]
 [2 1 7 6 8]
 [1 9 5 2 4]
 [7 8 6 6 7]]


**<code>np.random.uniform</code>**

* Returns a random numpy array whose element(s) are drawn randomly from low (inclusive) to the high (exclusive) range.

* <code>np.random.uniform(low-inclusive, high-exclusive, size)</code>

In [ ]:
# Generate a single random float between 0 and 1
random_float = np.random.uniform(0, 1)
print(random_float)

# Generate an array of random floats between -1 and 1
random_floats_array = np.random.uniform(-1, 1, size=5)
print(random_floats_array)

# Generate an array of random floats between -1 and 1
random_floats_matrix = np.random.uniform(-1, 1, size=[5,5])
print(random_floats_matrix)

0.1959306141809568
[-0.93390629 -0.8763171   0.26011077 -0.86368417 -0.88895515]
[[-0.44537031  0.40422156 -0.47762263  0.00500541 -0.52015092]
 [ 0.44440013  0.10669827 -0.21905662 -0.51921595  0.41370425]
 [-0.71593226  0.13438749  0.30412921  0.35126493  0.96210845]
 [ 0.29667131  0.91102319  0.19487548  0.18142295  0.28561713]
 [-0.2355449   0.00113651  0.16912922  0.80325752 -0.80552879]]


**Accessing the entries of a Numpy Array**

In [ ]:
# let's generate an array with 10 random values
rand_arr = np.arange(0,10)
print(rand_arr)

[0 1 2 3 4 5 6 7 8 9]


In [ ]:
# accessing the 7 th entry of rand_arr

print("1th ",rand_arr[0])
print("7th ",rand_arr[6])

1th  0
7th  6


**Accessing multiple elements from an array**

In [ ]:
# we can access multiple entries at once using
print(rand_arr[4:9])

[4 5 6 7 8]


In [ ]:
# we can also access multiple non-consecutive entries using np.arange
print('Index of values to access: ',3,5,6)
print(rand_arr[[3,5,6]])
print('Index of values to access: ',np.arange(3,10,3))
print(rand_arr[np.arange(3,10,3)])

Index of values to access:  3 5 6
[3 5 6]
Index of values to access:  [3 6 9]
[3 6 9]


**Accessing arrays using logical operations**

In [ ]:
print(rand_arr)

[0 1 2 3 4 5 6 7 8 9]


In [ ]:
rand_arr>0

array([False,  True,  True,  True,  True,  True,  True,  True,  True,
        True])

In [ ]:
# accessing all the values of rand_arr which are greater than 0
print('Values greater than 0: ',rand_arr[rand_arr>0])

# accessing all the values of rand_arr which are less than 0
print('Values less than 0: ',rand_arr[rand_arr<0])

Values greater than 0:  [1 2 3 4 5 6 7 8 9]
Values less than 0:  []


**Accessing the entries of a Matrix**

In [ ]:
# let's generate an array with 10 random values
rand_mat = np.random.randn(5,5)
print(rand_mat)

[[-1.83198975 -0.46914874 -1.01011287  0.56578285  0.11660963]
 [ 0.07456235  1.09797779 -0.51907958 -1.72803984  0.94691415]
 [ 0.87561231  0.68761233 -1.25168041  1.00726425  1.01495761]
 [-0.96374246  0.6387761   1.05583185  0.47654941  1.14561276]
 [-1.05451839  0.98117381 -2.13882533 -1.18657425 -0.05657434]]


In [ ]:
# acessing the second row of the rand_mat
rand_mat[1]

array([ 0.07456235,  1.09797779, -0.51907958, -1.72803984,  0.94691415])

In [ ]:
# acessing third element of the second row
print(rand_mat[1][2])

#or

print(rand_mat[1,2])

-0.5190795813379658
-0.5190795813379658


In [ ]:
# accessing first two rows with second and third column
print(rand_mat[0:2,1:3])

[[-0.46914874 -1.01011287]
 [ 1.09797779 -0.51907958]]


**Accessing matrices using logical operations**

In [ ]:
print(rand_mat)

[[-1.83198975 -0.46914874 -1.01011287  0.56578285  0.11660963]
 [ 0.07456235  1.09797779 -0.51907958 -1.72803984  0.94691415]
 [ 0.87561231  0.68761233 -1.25168041  1.00726425  1.01495761]
 [-0.96374246  0.6387761   1.05583185  0.47654941  1.14561276]
 [-1.05451839  0.98117381 -2.13882533 -1.18657425 -0.05657434]]


In [ ]:
# accessing all the values of rand_mat which are greater than 0
print('Values greater than 0: \n ',rand_mat[rand_mat>0])

# accessing all the values of rand_mat which are less than 0
print('Values less than 0: \n',rand_mat[rand_mat<0])

Values greater than 0: 
  [0.56578285 0.11660963 0.07456235 1.09797779 0.94691415 0.87561231
 0.68761233 1.00726425 1.01495761 0.6387761  1.05583185 0.47654941
 1.14561276 0.98117381]
Values less than 0: 
 [-1.83198975 -0.46914874 -1.01011287 -0.51907958 -1.72803984 -1.25168041
 -0.96374246 -1.05451839 -2.13882533 -1.18657425 -0.05657434]


**Modifying the entries of an Array**

In [ ]:
print(rand_arr)

[0 1 2 3 4 5 6 7 8 9]


In [ ]:
# let's change some values in an array!
# changing the values of index value 3 and index value 4 to 5
rand_arr[3:5] = 5
print(rand_arr)

[0 1 2 5 5 5 6 7 8 9]


In [ ]:
# changing the values of index value 0 and index value 1 to 2 and 3 respectively
rand_arr[0:2] = [2,3]
print(rand_arr)

[2 3 2 5 5 5 6 7 8 9]


In [ ]:
# modify entries using logical references
rand_arr[rand_arr>0] = 65
rand_arr

array([65, 65, 65, 65, 65, 65, 65, 65, 65, 65])

**Modifying the entries of a Matrix**

In [ ]:
print(rand_mat3)

[[5 2 4 2 5]
 [6 3 5 8 7]
 [2 1 7 6 8]
 [1 9 5 2 4]
 [7 8 6 6 7]]


In [ ]:
# changing the values of the 4th and 5th element of the second and third rows of the matrix to 0
print('Matrix before modification: \n',rand_mat3)
rand_mat3[1:3,3:5] = 0
print('Matrix after modification: \n',rand_mat3)

Matrix before modification: 
 [[5 2 4 2 5]
 [6 3 5 8 7]
 [2 1 7 6 8]
 [1 9 5 2 4]
 [7 8 6 6 7]]
Matrix after modification: 
 [[5 2 4 2 5]
 [6 3 5 0 0]
 [2 1 7 0 0]
 [1 9 5 2 4]
 [7 8 6 6 7]]


In [ ]:
# extracting the first 2 rows and first 3 columns from the matrix
sub_mat = rand_mat[0:2,0:3]
print(sub_mat)

[[-1.83198975 -0.46914874 -1.01011287]
 [ 0.07456235  1.09797779 -0.51907958]]


In [ ]:
# changing all the values of the extracted matrix to 3
sub_mat[:] = 3
print(sub_mat)

[[3. 3. 3.]
 [3. 3. 3.]]


In [ ]:
# what happened to rand_mat when we change sub_mat?
rand_mat

array([[ 3.        ,  3.        ,  3.        ,  0.56578285,  0.11660963],
       [ 3.        ,  3.        ,  3.        , -1.72803984,  0.94691415],
       [ 0.87561231,  0.68761233, -1.25168041,  1.00726425,  1.01495761],
       [-0.96374246,  0.6387761 ,  1.05583185,  0.47654941,  1.14561276],
       [-1.05451839,  0.98117381, -2.13882533, -1.18657425, -0.05657434]])

In [ ]:
# to prevent this behavior we need to use the .copy() method when we assign sub_mat
# this behavior is the source of MANY errors for early python users!!!

rand_mat = np.random.randn(5,5)
print(rand_mat)
sub_mat = rand_mat[0:2,0:3].copy()
sub_mat[:] = 3
print(sub_mat)
print(rand_mat)

[[-1.2620089   0.06322711  2.24900497  0.13052506  0.1656314 ]
 [ 0.38415671  0.6351065   0.748111   -1.82355971  1.65411267]
 [ 1.23706201  0.67681381 -0.06378509 -1.24341467  1.81210914]
 [ 0.65371784 -0.01917039  0.49844114 -1.54942795 -0.53175431]
 [-0.03060107 -1.03328453  1.63049349  0.44805056  1.04156045]]
[[3. 3. 3.]
 [3. 3. 3.]]
[[-1.2620089   0.06322711  2.24900497  0.13052506  0.1656314 ]
 [ 0.38415671  0.6351065   0.748111   -1.82355971  1.65411267]
 [ 1.23706201  0.67681381 -0.06378509 -1.24341467  1.81210914]
 [ 0.65371784 -0.01917039  0.49844114 -1.54942795 -0.53175431]
 [-0.03060107 -1.03328453  1.63049349  0.44805056  1.04156045]]


**Saving and Loading a NumPy array**

In [ ]:
#from google.colab import drive
#drive.mount('/content/drive')

In [ ]:
# creating a random matrices
randint_matrix1 = np.random.randint(1,10,10).reshape(2,5)
print(randint_matrix1)
print('')
randint_matrix2 = np.random.randint(10,20,10).reshape(2,5)
print(randint_matrix2)

[[4 3 1 5 2]
 [6 7 2 7 3]]

[[19 16 15 11 19]
 [15 11 10 12 19]]


**Using np.save() function**

In [ ]:
#np.save('/content/drive/MyDrive/Python Course/saved_file_name',randint_matrix1)
np.save("single_file",randint_matrix1)

**Using np.savez() function**

In [ ]:
#np.savez('/content/drive/MyDrive/Python Course/multiple_files',randint_matrix1=randint_matrix1,randint_matrix2=randint_matrix2)
np.savez('multiple_files',randint_matrix1=randint_matrix1,randint_matrix2=randint_matrix2)

* The files will be saved in the directory where the Jupyter Notebook is located.
* With np.save() function, we can save an array/matrix to a NumPy .npy format.
* np.savez() function has an advantage over np.save() function because with np.savez(), we can store several arrays/matrices into a single file in uncompressed .npz format.

In [ ]:
# now let's load it
#loaded_arr = np.load('/content/drive/MyDrive/Python Course/single_file.npy')
#loaded_multi = np.load('/content/drive/MyDrive/Python Course/multiple_files.npz')

loaded_arr = np.load('single_file.npy')
loaded_multi = np.load('multiple_files.npz')


print(loaded_arr)
print('')
print(loaded_multi)

[[4 3 1 5 2]
 [6 7 2 7 3]]



* We see that .npy file has been loaded but the .npz file is returning a memory location.
* Let's see how to load the values stored in .npz file.

In [ ]:
print('1st Matrix: \n',loaded_multi['randint_matrix1'])
print('2nd Matrix: \n',loaded_multi['randint_matrix2'])

new_matrix  = loaded_multi['randint_matrix1']
print('New Matrix: \n',new_matrix)

1st Matrix: 
 [[4 3 1 5 2]
 [6 7 2 7 3]]
2nd Matrix: 
 [[19 16 15 11 19]
 [15 11 10 12 19]]
New Matrix: 
 [[4 3 1 5 2]
 [6 7 2 7 3]]


In [ ]:
# we can also save/load text files...but only single variables
np.savetxt('text_file_name.txt',randint_matrix1,delimiter=',')
rand_mat_txt = np.loadtxt('text_file_name.txt',delimiter=',')
print(randint_matrix1)
print('')
print(rand_mat_txt)

[[4 3 1 5 2]
 [6 7 2 7 3]]

[[4. 3. 1. 5. 2.]
 [6. 7. 2. 7. 3.]]
